apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-livechat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EdnaldoLourenco/homelab.git
    targetRevision: main
    path: apps/will/livechat
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
