apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-pgadmin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.runix.net/
      chart: pgadmin4
      targetRevision: 1.57.0
      helm:
        releaseName: pgadmin
        valueFiles: 
           - $values/database/pgadmin/pgadmin-values.yaml

    - repoURL: https://github.com/EdnaldoLourenco/homelab.git
      targetRevision: main
      ref:  values

  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
