apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-argocd-imageupdater
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: 1.0.5
      helm:
        releaseName: argocd-image-updater
        valueFiles:
          - $values/infra/ArgoCD/argocd-image-updater-values.yaml

    - repoURL: https://github.com/EdnaldoLourenco/homelab.git
      targetRevision: main
      ref:  values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
