apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-cert-manager
  namespace: argocd
spec:
  project: default
  sources:

    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.19.2
      helm:
        releaseName: cert-manager
        valueFiles: 
          - $values/infra/cert-manager/helm/cert-manager-values.yaml

    - repoURL: https://github.com/EdnaldoLourenco/homelab.git
      targetRevision: main
      ref:  values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
