apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kp
  namespace: argocd
  argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 81.0.1
      helm:
        releaseName: kp
        valueFiles: 
           - $values/monitoring/prometheus/kp-values.yaml

    - repoURL: https://github.com/EdnaldoLourenco/homelab.git
      targetRevision: main
      ref:  values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
