apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.10.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/infra/storage/longhorn-values.yaml

    - repoURL: https://github.com/EdnaldoLourenco/homelab.git
      targetRevision: main
      ref:  values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
